# Generated by Django 5.0 on 2023-12-19 07:26

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[webapp.models.validate_description], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.models.validate_summary], verbose_name='Краткое описание'),
        ),
    ]
